### ISSUE TITLE
evaluate.py 

### ISSUE THREAD

**Issue by 2017develper** [ColeMurray/tensorflow-cnn-tutorial#1]
Can you help me please i have this error 

python evaluate.py
Traceback (most recent call last):
  File "evaluate.py", line 35, in <module>
    tf.app.run()
  File "C:\Users\USER\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "evaluate.py", line 28, in main
    evaluate()
  File "evaluate.py", line 11, in evaluate
    images, labels = mnist.load_test_data(FLAGS.test_data)
  File "C:\Users\USER\Desktop\hala_training\tensorflow-cnn-tutorial-add_model_functions\mnist_conv2d_medium_tutorial\mnist.py", line 45, in load_test_data
    x_test = x_test.reshape(len(x_test), IMAGE_SIZE, IMAGE_SIZE, 1)
  File "C:\Users\USER\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\pandas\core\generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)

**Comment by ColeMurray** [comment]
Hello 2017develper,

Have you downloaded the test data?

Links can be found here:
train_csv: https://pjreddie.com/media/files/mnist_train.csv
test_csv: https://pjreddie.com/media/files/mnist_test.csv

**Comment by 2017develper** [comment]
yes

**Comment by 2017develper** [comment]
@ColeMurray yes i downloaded it
